language: java
jdk:
  - openjdk18

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - daco.inc.v@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="2368f14d-9968-410a-b7ee-15d816b5f5f5"